"""create system_flags table

Revision ID: 071d3c999449
Revises: 735848582c28
Create Date: 2026-07-17 11:21:10.438632

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071d3c999449'
down_revision: Union[str, Sequence[str], None] = '735848582c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


system_flags_table = sa.table(
    "system_flags",
    sa.column("key", sa.String),
    sa.column("value", sa.Boolean),
    sa.column("updated_at", sa.DateTime),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_flags',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###

    # Hand-written (not autogenerated): seed the single kill-switch row —
    # AD-4 requires it to exist with a safe (disabled) default the moment
    # this table exists, matching Story 4.1's own AC verbatim.
    op.bulk_insert(
        system_flags_table,
        [{"key": "kill_switch_enabled", "value": False, "updated_at": datetime.utcnow()}],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_flags')
    # ### end Alembic commands ###
