"""create telegram_channel_config_changes table

Revision ID: 35deb2a05b15
Revises: d3f6b1c9a4e7
Create Date: 2026-08-10 00:00:00.000000

Hand-written, not autogenerated -- same reasoning as every other manual
migration in this project.

Audit trail for the "Alert Telegram" page's Bot Token/Chat ID saves --
see shared/models.py::TelegramChannelConfigChange for the full design
note on why this is its own table, not an AuditEntry row.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35deb2a05b15'
down_revision: Union[str, Sequence[str], None] = 'd3f6b1c9a4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'telegram_channel_config_changes',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('channel', sa.String(length=16), nullable=False),
        sa.Column('chat_id', sa.String(length=64), nullable=False),
        sa.Column('bot_token_masked', sa.String(length=32), nullable=False),
        sa.Column('actor', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'ix_telegram_channel_config_changes_channel',
        'telegram_channel_config_changes',
        ['channel'],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_telegram_channel_config_changes_channel', table_name='telegram_channel_config_changes')
    op.drop_table('telegram_channel_config_changes')
