"""add rationale and target_nodes to actions

Revision ID: 3859af1d019a
Revises: 38e5c190a9f4
Create Date: 2026-07-17 18:59:15.143622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3859af1d019a'
down_revision: Union[str, Sequence[str], None] = '38e5c190a9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('rationale', sa.Text(), nullable=True))
    op.add_column('actions', sa.Column('target_nodes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'target_nodes')
    op.drop_column('actions', 'rationale')
    # ### end Alembic commands ###
