"""add mgr/osd/rgw nodes to clusters

Revision ID: 3db378f53908
Revises: 35deb2a05b15
Create Date: 2026-08-10 00:00:00.000000

Hand-written, not autogenerated -- same reasoning as every other manual
migration in this project.

Multi-tenant remediation Phase 1 -- shared/models.py::Cluster gains the
remaining node-role fields (mgr/osd/rgw) + rgw container name so a
Cluster row can fully stand in for config/settings.py's Settings
singleton on a per-cluster basis (see shared/cluster_nodes.py::
configured_nodes()/resolve_ssh_creds()).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db378f53908'
down_revision: Union[str, Sequence[str], None] = '35deb2a05b15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('clusters', sa.Column('ceph_mgr_nodes', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('ceph_osd_nodes', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('ceph_rgw_nodes', sa.Text(), nullable=False, server_default=''))
    op.add_column(
        'clusters', sa.Column('ceph_rgw_container_name', sa.String(length=128), nullable=False, server_default='')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('clusters', 'ceph_rgw_container_name')
    op.drop_column('clusters', 'ceph_rgw_nodes')
    op.drop_column('clusters', 'ceph_osd_nodes')
    op.drop_column('clusters', 'ceph_mgr_nodes')
