"""add mon hostnames + osd container to clusters

Revision ID: 59bef6f2182f
Revises: 3db378f53908
Create Date: 2026-08-10 00:10:00.000000

Hand-written, not autogenerated -- same reasoning as every other manual
migration in this project.

Multi-tenant remediation Phase 1, continued -- watcher/collector.py's log
collection (identify_relevant_nodes/_log_command_for_host) also needs
per-cluster MON hostnames (for mon-name -> IP resolution parsed out of
`ceph health detail` text) and the OSD daemon's own container name
(separate from ceph_container_name, which is MON's) to become
cluster-aware, so this follows right behind 3db378f53908 rather than
being folded into it -- that migration was already applied before this
gap was found.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bef6f2182f'
down_revision: Union[str, Sequence[str], None] = '3db378f53908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('clusters', sa.Column('ceph_mon_hostnames', sa.Text(), nullable=False, server_default=''))
    op.add_column(
        'clusters', sa.Column('ceph_osd_container_name', sa.String(length=128), nullable=False, server_default='')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('clusters', 'ceph_osd_container_name')
    op.drop_column('clusters', 'ceph_mon_hostnames')
