"""create log intelligence tables

Log Intelligence & AI RCA, bước L0 (Plan/log-intelligence-rca-plan.md).

Hand-written (not autogenerated). Ba bảng, cố ý KHÔNG có bảng nào chứa log
thô -- xem ràng buộc R1 của plan và `watcher/database_capacity_monitor.py`
(database của chính app này là tài nguyên có giám sát/cảnh báo, nên log thô
ở lại nguồn, chỉ fingerprint + số đếm được lưu):

- `log_ingest_runs`: một dòng mỗi lần quét, ghi độ đầy đủ của evidence.
- `log_patterns`: một dòng mỗi LOẠI dòng log (đã bỏ biến số).
- `log_pattern_observations`: số đếm theo giờ -- bảng duy nhất phình theo
  khối lượng log, nên có retention riêng ngắn hơn hẳn.

Revision ID: 6192ad592f06
Revises: 5bdecca5014e
Create Date: 2026-08-18

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6192ad592f06'
# 2026-08-18: re-pointed from the original '2a98d04f2f06' (a redundant
# "drop system_flags" migration that tried to drop a table an earlier,
# already-committed migration — c8d2f4a901be, "remove obsolete system
# flags storage" — had already removed years prior; broke `alembic upgrade
# head` on any fresh DB with "no such table: system_flags" and was
# deleted, not applied to any real database) onto the AI-roadmap Pha 0.4
# safety-policy-hardening migration instead, since this migration's own 3
# new tables have no relationship to system_flags either way.
down_revision: Union[str, Sequence[str], None] = '5bdecca5014e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'log_ingest_runs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('cluster_id', sa.String(length=36), nullable=False),
        sa.Column('source', sa.String(length=16), nullable=False),
        sa.Column('window_start', sa.DateTime(), nullable=False),
        sa.Column('window_end', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('hosts_scanned', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('hosts_failed', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('lines_scanned', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('patterns_seen', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('patterns_new', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint(
            "status IN ('OK','PARTIAL','FAILED')",
            name='ck_log_ingest_runs_status_valid',
        ),
    )
    op.create_index('ix_log_ingest_runs_cluster_id', 'log_ingest_runs', ['cluster_id'])
    op.create_index('ix_log_ingest_runs_created_at', 'log_ingest_runs', ['created_at'])

    op.create_table(
        'log_patterns',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('cluster_id', sa.String(length=36), nullable=False),
        sa.Column('fingerprint', sa.String(length=40), nullable=False),
        sa.Column('template', sa.Text(), nullable=False),
        sa.Column('daemon_type', sa.String(length=8), nullable=False),
        sa.Column('severity', sa.Integer(), nullable=True),
        sa.Column('sample_line', sa.Text(), nullable=True),
        sa.Column('first_seen_at', sa.DateTime(), nullable=False),
        sa.Column('last_seen_at', sa.DateTime(), nullable=False),
        sa.Column('total_count', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('triage_label', sa.String(length=16), nullable=False, server_default='UNKNOWN'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cluster_id', 'fingerprint', name='uq_log_patterns_cluster_fingerprint'),
        sa.CheckConstraint(
            "triage_label IN ('UNKNOWN','BENIGN','NOTABLE')",
            name='ck_log_patterns_triage_label_valid',
        ),
    )
    op.create_index('ix_log_patterns_cluster_id', 'log_patterns', ['cluster_id'])
    op.create_index('ix_log_patterns_fingerprint', 'log_patterns', ['fingerprint'])
    op.create_index('ix_log_patterns_daemon_type', 'log_patterns', ['daemon_type'])
    op.create_index('ix_log_patterns_first_seen_at', 'log_patterns', ['first_seen_at'])
    op.create_index('ix_log_patterns_last_seen_at', 'log_patterns', ['last_seen_at'])

    op.create_table(
        'log_pattern_observations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('pattern_id', sa.String(length=36), nullable=False),
        sa.Column('bucket_hour', sa.DateTime(), nullable=False),
        sa.Column('host', sa.String(length=64), nullable=False),
        sa.Column('count', sa.BigInteger(), nullable=False, server_default='0'),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['pattern_id'], ['log_patterns.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'pattern_id', 'bucket_hour', 'host', name='uq_log_pattern_observations_bucket'
        ),
    )
    op.create_index(
        'ix_log_pattern_observations_pattern_id', 'log_pattern_observations', ['pattern_id']
    )
    op.create_index(
        'ix_log_pattern_observations_bucket_hour', 'log_pattern_observations', ['bucket_hour']
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('log_pattern_observations')
    op.drop_table('log_patterns')
    op.drop_table('log_ingest_runs')
