"""create actions table

Revision ID: 735848582c28
Revises: f2b28bda4f37
Create Date: 2026-07-17 10:12:43.752733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735848582c28'
down_revision: Union[str, Sequence[str], None] = 'f2b28bda4f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('proposed_command', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("classification IN ('SAFE','RISKY')", name='ck_actions_classification_valid'),
    sa.CheckConstraint("status IN ('PENDING','AUTO_EXECUTED','PENDING_APPROVAL','APPROVED','REJECTED','EXECUTED','FAILED')", name='ck_actions_status_valid'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    # ### end Alembic commands ###
