"""create node_upgrade_gate and lock tables

Revision ID: 91d7e9723457
Revises: 38df461ab6d0
Create Date: 2026-08-05 00:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '91d7e9723457'
down_revision: Union[str, Sequence[str], None] = '38df461ab6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


node_upgrade_gate_locks_table = sa.table(
    "node_upgrade_gate_locks",
    sa.column("id", sa.String),
    sa.column("active_gate_id", sa.String),
)


def upgrade() -> None:
    op.create_table(
        'node_upgrade_gates',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('host', sa.String(length=64), nullable=False),
        sa.Column('target_version', sa.String(length=32), nullable=False),
        sa.Column('state', sa.String(length=32), nullable=False),
        sa.Column('roles_snapshot', sa.Text(), nullable=True),
        sa.Column('osd_backup', sa.Text(), nullable=True),
        sa.Column('prepare_action_id', sa.String(length=36), nullable=True),
        sa.Column('confirm_action_id', sa.String(length=36), nullable=True),
        sa.Column('abort_action_id', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "state IN ('PREPARING','PREPARED','RECOVERING','ABORTING','DONE','FAILED')",
            name='ck_node_upgrade_gates_state_valid',
        ),
        sa.ForeignKeyConstraint(['prepare_action_id'], ['actions.id']),
        sa.ForeignKeyConstraint(['confirm_action_id'], ['actions.id']),
        sa.ForeignKeyConstraint(['abort_action_id'], ['actions.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'node_upgrade_gate_locks',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('active_gate_id', sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )

    # Hand-written (not autogenerated): seed the single lock row so
    # claim_node_upgrade_gate_lock's `WHERE id = 'singleton'` CAS UPDATE has
    # a row to match against from the moment this table exists — an UPDATE
    # against a non-existent row is a silent 0-rowcount no-op, which would
    # be indistinguishable from "lock already held" (AC #2).
    op.bulk_insert(
        node_upgrade_gate_locks_table,
        [{"id": "singleton", "active_gate_id": None}],
    )


def downgrade() -> None:
    op.drop_table('node_upgrade_gate_locks')
    op.drop_table('node_upgrade_gates')
