"""add telegram channel to clusters

Revision ID: 94de522c29f3
Revises: 59bef6f2182f
Create Date: 2026-08-10 01:00:00.000000

Hand-written, not autogenerated -- same reasoning as every other manual
migration in this project.

Multi-tenant remediation Phase 2 -- one Telegram channel (Bot Token/Chat
ID/enabled) per ADDITIONAL Cluster row, so its alerts/RISKY approvals can
be narrowed to its own chat instead of always broadcasting to the 3
global channels. See shared/models.py::Cluster's own docstring for why
this is a single channel, not the default cluster's 3-category split.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94de522c29f3'
down_revision: Union[str, Sequence[str], None] = '59bef6f2182f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('clusters', sa.Column('telegram_bot_token', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('telegram_chat_id', sa.String(length=64), nullable=False, server_default=''))
    op.add_column(
        'clusters', sa.Column('telegram_enabled', sa.Boolean(), nullable=False, server_default=sa.true())
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('clusters', 'telegram_enabled')
    op.drop_column('clusters', 'telegram_chat_id')
    op.drop_column('clusters', 'telegram_bot_token')
