"""add ai conclusion columns to volume_perf_sweeps

Revision ID: a1b6a76b76f9
Revises: a2ed98ff2b47
Create Date: 2026-07-29 14:57:25.591838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b6a76b76f9'
down_revision: Union[str, Sequence[str], None] = 'a2ed98ff2b47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volume_perf_sweeps', sa.Column('ai_conclusion', sa.Text(), nullable=True))
    op.add_column('volume_perf_sweeps', sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volume_perf_sweeps', 'ai_analyzed_at')
    op.drop_column('volume_perf_sweeps', 'ai_conclusion')
    # ### end Alembic commands ###
