"""add backup config to clusters

Revision ID: a1c2f5d8e934
Revises: 94de522c29f3
Create Date: 2026-08-11 01:00:00.000000

Hand-written, not autogenerated -- same reasoning as every other manual
migration in this project.

Multi-tenant remediation Phase 3 -- one RBD backup target (own SSH or S3
credentials, deliberately separate from ssh_user/ssh_key_path used to
manage the source cluster, same PRD FR-4 posture config/settings.py's
backup_target_a/b_* fields already follow) per ADDITIONAL Cluster row, off
by default. See shared/models.py::Cluster's own docstring.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c2f5d8e934'
down_revision: Union[str, Sequence[str], None] = '94de522c29f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('clusters', sa.Column('backup_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('clusters', sa.Column('backup_tracked_images', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_full_refresh_days', sa.Integer(), nullable=True))
    op.add_column('clusters', sa.Column('backup_transport', sa.String(length=16), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_ssh_host', sa.String(length=255), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_ssh_user', sa.String(length=64), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_ssh_key_path', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_ssh_landing_dir', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_s3_endpoint', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_s3_access_key', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_s3_secret_key', sa.Text(), nullable=False, server_default=''))
    op.add_column('clusters', sa.Column('backup_s3_bucket', sa.String(length=255), nullable=False, server_default=''))
    op.add_column(
        'clusters', sa.Column('backup_immutable_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column(
        'clusters', sa.Column('backup_immutable_lock_days', sa.Integer(), nullable=False, server_default='7')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('clusters', 'backup_immutable_lock_days')
    op.drop_column('clusters', 'backup_immutable_enabled')
    op.drop_column('clusters', 'backup_s3_bucket')
    op.drop_column('clusters', 'backup_s3_secret_key')
    op.drop_column('clusters', 'backup_s3_access_key')
    op.drop_column('clusters', 'backup_s3_endpoint')
    op.drop_column('clusters', 'backup_ssh_landing_dir')
    op.drop_column('clusters', 'backup_ssh_key_path')
    op.drop_column('clusters', 'backup_ssh_user')
    op.drop_column('clusters', 'backup_ssh_host')
    op.drop_column('clusters', 'backup_transport')
    op.drop_column('clusters', 'backup_full_refresh_days')
    op.drop_column('clusters', 'backup_tracked_images')
    op.drop_column('clusters', 'backup_enabled')
