"""create volume_perf_sweeps table

Revision ID: a2ed98ff2b47
Revises: e082bc0d48af
Create Date: 2026-07-29 10:00:47.003733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ed98ff2b47'
down_revision: Union[str, Sequence[str], None] = 'e082bc0d48af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume_perf_sweeps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=False),
    sa.Column('pool', sa.String(length=64), nullable=False),
    sa.Column('scratch_image', sa.String(length=128), nullable=False),
    sa.Column('requested_by', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('steps_json', sa.Text(), nullable=False),
    sa.Column('knee_iodepth', sa.Integer(), nullable=True),
    sa.Column('knee_iops', sa.Float(), nullable=True),
    sa.Column('knee_latency_avg_ms', sa.Float(), nullable=True),
    sa.Column('knee_latency_p99_ms', sa.Float(), nullable=True),
    sa.Column('qos_notes', sa.Text(), nullable=True),
    sa.Column('bottleneck_notes', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_volume_perf_sweeps_pool_scratch_image_created_at', 'volume_perf_sweeps', ['pool', 'scratch_image', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_volume_perf_sweeps_pool_scratch_image_created_at', table_name='volume_perf_sweeps')
    op.drop_table('volume_perf_sweeps')
    # ### end Alembic commands ###
