"""create backup_digest_logs table

Revision ID: ae06e189e701
Revises: 2d1159f2d7fc
Create Date: 2026-07-31 09:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ae06e189e701'
down_revision: Union[str, Sequence[str], None] = '2d1159f2d7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Hand-written, not autogenerated — the production DB is currently one
# migration behind this chain's head (Story 9.1's daae81bc54e6 is the last
# one actually applied there), and `alembic revision --autogenerate`
# refuses to diff against a DB that isn't at head. The shape here matches
# `shared/models.py::BackupDigestLog` exactly; verify against that model
# if this ever needs re-generating for real.


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('backup_digest_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('anomaly_count', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('backup_digest_logs')
