"""add cluster_id to backup_jobs

Revision ID: b7e39a2c410f
Revises: a1c2f5d8e934
Create Date: 2026-08-11 01:15:00.000000

Hand-written, not autogenerated -- same reasoning as every other manual
migration in this project.

Multi-tenant remediation Phase 3 -- NULL means the default cluster, same
semantics as incidents.cluster_id (no backfill needed: every existing row
predates multi-cluster backup and correctly means "the default cluster").
Also widens backup_target_slot from 1 char ("a"/"b") to 16 so an
additional cluster's single-target jobs can be stamped with the fixed
marker "cluster" (see shared/models.py::BackupJob's own comment).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e39a2c410f'
down_revision: Union[str, Sequence[str], None] = 'a1c2f5d8e934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('backup_jobs', sa.Column('cluster_id', sa.String(length=36), nullable=True))
    with op.batch_alter_table('backup_jobs') as batch_op:
        batch_op.create_foreign_key('fk_backup_jobs_cluster_id', 'clusters', ['cluster_id'], ['id'])
        batch_op.alter_column('backup_target_slot', type_=sa.String(length=16), existing_type=sa.String(length=1))
    op.create_index('ix_backup_jobs_cluster_id', 'backup_jobs', ['cluster_id'])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_backup_jobs_cluster_id', table_name='backup_jobs')
    with op.batch_alter_table('backup_jobs') as batch_op:
        batch_op.alter_column('backup_target_slot', type_=sa.String(length=1), existing_type=sa.String(length=16))
        batch_op.drop_constraint('fk_backup_jobs_cluster_id', type_='foreignkey')
    op.drop_column('backup_jobs', 'cluster_id')
