"""create backup_jobs table

Revision ID: daae81bc54e6
Revises: a1b6a76b76f9
Create Date: 2026-07-30 23:48:55.227210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daae81bc54e6'
down_revision: Union[str, Sequence[str], None] = 'a1b6a76b76f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('pool', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.Column('job_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('base_job_id', sa.String(length=36), nullable=True),
    sa.Column('backup_target_slot', sa.String(length=1), nullable=True),
    sa.Column('remote_key', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_job_id'], ['backup_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_jobs_pool_image_created_at', 'backup_jobs', ['pool', 'image', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_backup_jobs_pool_image_created_at', table_name='backup_jobs')
    op.drop_table('backup_jobs')
    # ### end Alembic commands ###
