"""create volume_metrics table

Revision ID: e082bc0d48af
Revises: 9f1c2a7d5e3b
Create Date: 2026-07-28 13:10:36.189012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e082bc0d48af'
down_revision: Union[str, Sequence[str], None] = '9f1c2a7d5e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volume_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool', sa.String(length=64), nullable=False),
    sa.Column('image', sa.String(length=128), nullable=False),
    sa.Column('iops', sa.Float(), nullable=False),
    sa.Column('read_latency_ms', sa.Float(), nullable=False),
    sa.Column('write_latency_ms', sa.Float(), nullable=False),
    sa.Column('saturated', sa.Boolean(), nullable=False),
    sa.Column('polled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_volume_metrics_pool_image_polled_at', 'volume_metrics', ['pool', 'image', 'polled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_volume_metrics_pool_image_polled_at', table_name='volume_metrics')
    op.drop_table('volume_metrics')
    # ### end Alembic commands ###
