"""add diagnosis_text to incidents

Revision ID: f2b28bda4f37
Revises: 1bd5de967b1a
Create Date: 2026-07-17 08:22:33.951439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2b28bda4f37'
down_revision: Union[str, Sequence[str], None] = '1bd5de967b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('diagnosis_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'diagnosis_text')
    # ### end Alembic commands ###
