"""create test_runner_configs table

Revision ID: f5f9c4cd268f
Revises: ae06e189e701
Create Date: 2026-08-04 00:00:00.000000

Hand-written, not autogenerated -- same reasoning as ae06e189e701 (the
production DB is intentionally kept one migration behind head, so
`alembic revision --autogenerate` would diff against a schema this dev
environment doesn't actually have applied there).

Epic 10 Story 10.2 -- singleton config row for the Test Runner's RGW test
endpoints, test-group/priority selection, and which of the 7 fixed
baseline files have been uploaded. See shared/models.py::TestRunnerConfig.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f9c4cd268f'
down_revision: Union[str, Sequence[str], None] = 'ae06e189e701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('test_runner_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rgw_endpoint_zone_a', sa.String(length=255), nullable=True),
    sa.Column('rgw_endpoint_zone_b', sa.String(length=255), nullable=True),
    sa.Column('rgw_endpoint_vip', sa.String(length=255), nullable=True),
    sa.Column('test_groups', sa.Text(), nullable=True),
    sa.Column('priorities', sa.Text(), nullable=True),
    sa.Column('baseline_files', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('test_runner_configs')
