from sqlalchemy import or_, update
from sqlalchemy.orm import Session

from shared.models import NodeUpgradeGate, NodeUpgradeGateLock, NodeUpgradeGateState

LOCK_ID = "singleton"

_NON_TERMINAL_STATES = (
    NodeUpgradeGateState.PREPARING.value,
    NodeUpgradeGateState.PREPARED.value,
    NodeUpgradeGateState.RECOVERING.value,
    NodeUpgradeGateState.ABORTING.value,
)


def claim_node_upgrade_gate_lock(session: Session, gate_id: str) -> bool:
    """AD-24: the ONLY mechanism that actually enforces "at most one node
    mid-flight" -- an atomic conditional UPDATE, safe against concurrent
    callers because the database serializes writers to the same row.

    `gate_id` is generated by the caller BEFORE the corresponding
    `NodeUpgradeGate` row is inserted (see `shared/models.py::
    NodeUpgradeGateLock`'s docstring for why `active_gate_id` has no FK).

    Returns True if this call won the claim (rowcount == 1), False if the
    lock was already held by another gate (rowcount == 0).
    """
    result = session.execute(
        update(NodeUpgradeGateLock)
        .where(NodeUpgradeGateLock.id == LOCK_ID, NodeUpgradeGateLock.active_gate_id.is_(None))
        .values(active_gate_id=gate_id)
    )
    return result.rowcount == 1


def release_node_upgrade_gate_lock(session: Session, gate_id: str) -> None:
    """AD-24: called the moment a `NodeUpgradeGate.state` reaches a
    terminal state (DONE/FAILED). Only releases if `gate_id` is the
    current holder -- a stale/already-released call is a harmless no-op.

    Does NOT commit -- caller controls the transaction boundary.
    """
    session.execute(
        update(NodeUpgradeGateLock)
        .where(NodeUpgradeGateLock.active_gate_id == gate_id)
        .values(active_gate_id=None)
    )


def _not_this_action(column, action_id: str):
    # NULL-safe: a bare `column != action_id` is three-valued SQL logic --
    # when column IS NULL (true for confirm_action_id/abort_action_id on
    # almost every row), `NULL != 'x'` is NULL, not True, which would
    # silently drop that row out of an ANDed WHERE clause even when it's a
    # genuinely different gate that should still count as "pending".
    return or_(column.is_(None), column != action_id)


def is_node_upgrade_gate_pending(session: Session, exclude_action_id: str | None = None) -> bool:
    """AD-19: defense-in-depth SELECT check, NOT the safety boundary
    (AD-24's CAS lock is) -- fast user-facing rejection with a clearer
    error message. True if any `NodeUpgradeGate` row is in a non-terminal
    state (PREPARING/PREPARED/RECOVERING/ABORTING).

    `exclude_action_id`: excludes the row (if any) that THIS action_id
    belongs to (prepare_action_id/confirm_action_id/abort_action_id) --
    Reviewer Gate CRITICAL finding #2's fix. The exemption MUST be
    row-specific, never "any action_id in the node_os_gate_* family" (a
    family-wide exemption would let a second node's own Prepare approval
    skip this check entirely, reopening the exact TOCTOU race AD-24's lock
    exists to close).
    """
    query = session.query(NodeUpgradeGate).filter(NodeUpgradeGate.state.in_(_NON_TERMINAL_STATES))
    if exclude_action_id is not None:
        query = query.filter(
            _not_this_action(NodeUpgradeGate.prepare_action_id, exclude_action_id),
            _not_this_action(NodeUpgradeGate.confirm_action_id, exclude_action_id),
            _not_this_action(NodeUpgradeGate.abort_action_id, exclude_action_id),
        )
    return query.first() is not None
